# Generated by Django 5.1.1 on 2024-09-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='disease',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
